"""True-vs-predicted prevalence diagonal plot (multiple-sample diagnostic)."""

import numpy as np

from ._base import (
    _check_ax,
    _color_cycle,
    _default_class_names,
    _validate_style_kwargs,
)


class DiagonalDisplay:
    """True vs. predicted prevalence diagonal plot.

    The signature diagnostic of quantification evaluation: across the many test
    samples generated by an evaluation protocol (e.g. APP/UPP), each sample's
    *predicted* prevalence is plotted against its *true* prevalence, together
    with the :math:`y = x` reference line. Points above the diagonal are
    over-estimates; points below are under-estimates. Tight clustering around
    the diagonal across the whole prevalence range indicates a good quantifier.

    This is a *multiple-sample* display: it summarises a protocol run rather
    than a single prediction.

    Parameters
    ----------
    true_prevalences : ndarray of shape (n_samples, n_classes)
        True class prevalence of each evaluation sample.
    predicted_prevalences : ndarray of shape (n_samples, n_classes)
        Predicted class prevalence of each evaluation sample.
    class_names : list of str, default=None
        Class labels, in the column order of the prevalence arrays.

    Attributes
    ----------
    scatter_ : matplotlib PathCollection or list of PathCollection
        The scatter artist(s). A list when several classes are drawn.
    line_ : matplotlib Line2D
        The :math:`y = x` reference line.
    ax_ : matplotlib Axes
        The axes with the plot.
    figure_ : matplotlib Figure
        The figure containing the axes.

    See Also
    --------
    BiasDisplay : Boxplots of signed estimation error.
    ErrorByShiftDisplay : Error as a function of prior-probability shift.

    Examples
    --------
    >>> from mlquantify.visualization import DiagonalDisplay
    >>> from mlquantify.counting import CC
    >>> from sklearn.linear_model import LogisticRegression
    >>> from sklearn.datasets import make_classification
    >>> X, y = make_classification(n_samples=400, random_state=0)
    >>> disp = DiagonalDisplay.from_protocol(   # doctest: +SKIP
    ...     CC(LogisticRegression()), X, y, protocol="app", n_prevalences=11)
    >>> disp.ax_.set_title("CC")   # doctest: +SKIP
    """

    def __init__(self, true_prevalences, predicted_prevalences, *, class_names=None):
        self.true_prevalences = np.asarray(true_prevalences, dtype=float)
        self.predicted_prevalences = np.asarray(predicted_prevalences, dtype=float)
        self.class_names = class_names

    def plot(
        self,
        ax=None,
        *,
        class_index=None,
        name=None,
        plot_diagonal=True,
        diagonal_kw=None,
        **kwargs,
    ):
        """Plot the diagonal scatter.

        Parameters
        ----------
        ax : matplotlib Axes, default=None
            Axes to draw on. A new figure/axes is created when None.
        class_index : int, default=None
            Which class column to plot. Defaults to the last class for binary
            problems (the conventional "positive" class) and to *all* classes
            (color-coded) for multiclass problems.
        name : str, default=None
            Label used in the legend (binary / single-class case).
        plot_diagonal : bool, default=True
            Whether to draw the :math:`y = x` reference line.
        diagonal_kw : dict, default=None
            Keyword arguments forwarded to the reference-line ``ax.plot`` call.
        **kwargs
            Forwarded to ``ax.scatter`` (the primary artist).

        Returns
        -------
        display : DiagonalDisplay
            Object that stores the computed artists.
        """
        fig, ax = _check_ax(ax)
        n_classes = self.true_prevalences.shape[1]
        class_names = _default_class_names(self.class_names, n_classes)

        if class_index is None and n_classes > 2:
            indices = list(range(n_classes))
        else:
            if class_index is None:
                class_index = n_classes - 1
            indices = [class_index]

        scatter_kwargs = _validate_style_kwargs({"s": 15, "alpha": 0.6}, kwargs)
        colors = _color_cycle()
        self.scatter_ = []
        for i, ci in enumerate(indices):
            label = name if len(indices) == 1 else class_names[ci]
            kw = dict(scatter_kwargs)
            kw.setdefault("color", colors[ci % len(colors)] if len(indices) > 1 else colors[0])
            self.scatter_.append(
                ax.scatter(
                    self.true_prevalences[:, ci],
                    self.predicted_prevalences[:, ci],
                    label=label,
                    **kw,
                )
            )
        if len(self.scatter_) == 1:
            self.scatter_ = self.scatter_[0]

        self.line_ = None
        if plot_diagonal:
            diagonal_kw = _validate_style_kwargs(
                {"color": "grey", "linestyle": "--", "linewidth": 1, "label": "ideal"},
                diagonal_kw or {},
            )
            (self.line_,) = ax.plot([0, 1], [0, 1], **diagonal_kw)

        ax.set(
            xlim=(-0.02, 1.02),
            ylim=(-0.02, 1.02),
            xlabel="True prevalence",
            ylabel="Predicted prevalence",
            aspect="equal",
        )
        if name is not None or len(indices) > 1 or plot_diagonal:
            ax.legend(loc="best")

        self.ax_ = ax
        self.figure_ = fig
        return self

    @classmethod
    def from_predictions(
        cls,
        true_prevalences,
        predicted_prevalences,
        *,
        class_names=None,
        ax=None,
        **kwargs,
    ):
        """Build a :class:`DiagonalDisplay` from precomputed prevalence arrays.

        Parameters
        ----------
        true_prevalences, predicted_prevalences : ndarray of shape \
                (n_samples, n_classes)
            True and predicted prevalence of each evaluation sample, e.g. the
            ``'true_prevalences'`` / ``'predicted_prevalences'`` arrays returned
            by :func:`mlquantify.model_selection.apply_protocol`.
        class_names : list of str, default=None
            Class labels in column order.
        ax : matplotlib Axes, default=None
            Axes to draw on.
        **kwargs
            Passed to :meth:`plot`.

        Returns
        -------
        display : DiagonalDisplay
        """
        return cls(
            true_prevalences, predicted_prevalences, class_names=class_names
        ).plot(ax=ax, **kwargs)

    @classmethod
    def from_protocol(
        cls,
        quantifier,
        X,
        y,
        *,
        protocol="app",
        ax=None,
        name=None,
        class_index=None,
        plot_diagonal=True,
        diagonal_kw=None,
        **protocol_kwargs,
    ):
        """Run an evaluation protocol and plot the resulting diagonal.

        Thin wrapper around :func:`mlquantify.model_selection.apply_protocol`.

        Parameters
        ----------
        quantifier : BaseQuantifier
            Quantifier to evaluate.
        X, y : array-like
            Data the protocol samples from.
        protocol : {'app', 'npp', 'upp', 'ppp'} or BaseProtocol, default='app'
            Sampling protocol.
        ax : matplotlib Axes, default=None
            Axes to draw on.
        name : str, default=None
            Legend label (binary case).
        class_index : int, default=None
            Class column to plot (see :meth:`plot`).
        plot_diagonal : bool, default=True
            Whether to draw the reference line.
        diagonal_kw : dict, default=None
            Reference-line styling.
        **protocol_kwargs
            Forwarded to :func:`apply_protocol` (e.g. ``n_prevalences``,
            ``batch_size``, ``random_state``). Styling kwargs for the scatter
            are *not* accepted here; call :meth:`plot` directly for that.

        Returns
        -------
        display : DiagonalDisplay
        """
        from mlquantify.model_selection import apply_protocol

        results = apply_protocol(
            quantifier, X, y, protocol=protocol,
            return_predictions=True, **protocol_kwargs,
        )
        class_names = np.unique(y)
        return cls(
            results["true_prevalences"],
            results["predicted_prevalences"],
            class_names=class_names,
        ).plot(
            ax=ax,
            name=name,
            class_index=class_index,
            plot_diagonal=plot_diagonal,
            diagonal_kw=diagonal_kw,
        )
