name: Deploy Sphinx Docs to GitHub Pages

on:
  release:
    types: [published]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-autobuild sphinx-rtd-theme sphinxcontrib-sass \
                      sphinx-remove-toctrees sphinx_design matplotlib numpydoc \
                      sphinx_copybutton sphinxext-opengraph sphinx-prompt \
                      pydata_sphinx_theme mlquantify

      - name: Build documentation
        run: |
          sphinx-build -b html docs/source docs/build/

      - name: Verificar arquivos gerados
        run: ls -la docs/build/

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: docs/build/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Baixar artifact da documentação
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: docs/build/

      - name: Remover links simbólicos para evitar erros
        run: find docs/build/ -type l -delete

      - name: Verificar arquivos baixados
        run: ls -la docs/build/

      - name: Verificar tamanho da documentação
        run: du -sh docs/build/

      - name: Deploy GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
