name: Publish Python Package

on:
  push:
    tags:
      - 'v*'  # Dispara o workflow quando um novo tag com 'v' for criado (ex: v0.1.1)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Gerar arquivo de versão
        run: |
          echo "${GITHUB_REF##*/}" | sed 's/^v//' > VERSION.txt

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Construir o pacote
        run: python -m build

      - name: Publicar no PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Remover arquivo de versão
        run: rm VERSION.txt
